# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin


class FileReaderPlugin(BasePlugin):
    """
    文件阅读器插件 - 读取用户发送的文件并提取结构化文本供AI处理
    
    功能：
    1. 自动检测用户发送的文件（PDF、Word、Markdown、HTML、TXT、图片等）
    2. 调用GeneralParsers插件解析文件内容
    3. 根据用户配置的prompt模板处理文件内容
    4. 支持多种处理模式：总结、翻译、提取、问答等
    
    使用方法：
    1. 安装GeneralParsers插件
    2. 安装本插件
    3. 向机器人发送文件
    4. 告诉AI你想如何处理文件（总结、翻译、提取关键信息等）
    """
    
    async def initialize(self) -> None:
        """插件初始化"""
        pass
