# Auto generated by LangBot Plugin SDK.
# FileReader Event Listener - 处理文件消息
from __future__ import annotations

import os
import time
import mimetypes
import aiohttp
import logging
import base64
import struct
import re
from pathlib import Path
from typing import Optional, List, Tuple
from urllib.parse import urlparse, unquote, parse_qs

# chardet 是可选依赖，用于自动检测文件编码
try:
    import chardet

    HAS_CHARDET = True
except ImportError:
    HAS_CHARDET = False

# pycryptodome 是可选依赖，用于解密企业微信文件
try:
    from Crypto.Cipher import AES

    HAS_CRYPTO = True
    print(f'[FileReader] pycryptodome loaded successfully (Crypto.Cipher.AES)')
except ImportError as e1:
    print(f'[FileReader] Failed to import Crypto.Cipher: {e1}')
    try:
        from Cryptodome.Cipher import AES

        HAS_CRYPTO = True
        print(f'[FileReader] pycryptodome loaded successfully (Cryptodome.Cipher.AES)')
    except ImportError as e2:
        print(f'[FileReader] Failed to import Cryptodome.Cipher: {e2}')
        HAS_CRYPTO = False
        print(f'[FileReader] WARNING: pycryptodome not available, file decryption disabled')

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message
from langbot_plugin.api.entities.builtin.provider import message as provider_message

logger = logging.getLogger(__name__)

# 支持的文件MIME类型映射
SUPPORTED_MIME_TYPES = {
    'application/pdf': 'PDF文档',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Word文档',
    'application/msword': 'Word文档',
    'text/plain': '文本文件',
    'text/markdown': 'Markdown文件',
    'text/html': 'HTML文件',
    'text/csv': 'CSV文件',
    'application/json': 'JSON文件',
    'application/xml': 'XML文件',
    'text/xml': 'XML文件',
}

# 图片MIME类型
IMAGE_MIME_TYPES = {
    'image/png': 'PNG图片',
    'image/jpeg': 'JPEG图片',
    'image/jpg': 'JPG图片',
    'image/gif': 'GIF图片',
    'image/webp': 'WebP图片',
    'image/bmp': 'BMP图片',
    'image/tiff': 'TIFF图片',
}


class FileReaderEventListener(EventListener):
    """文件阅读器事件监听器 - 拦截文件消息并解析内容"""

    async def initialize(self):
        await super().initialize()
        logger.info('FileReaderEventListener initialized')

        # 初始化 AES 密钥（如果配置了 EncodingAESKey）
        self._aes_key = None
        self._init_aes_key()

        # 注册私聊消息处理器
        @self.handler(events.PersonNormalMessageReceived)
        async def handle_person_message(ctx: context.EventContext):
            logger.info('Handling person message')
            await self._handle_message(ctx)

        # 注册群聊消息处理器
        @self.handler(events.GroupNormalMessageReceived)
        async def handle_group_message(ctx: context.EventContext):
            logger.info('Handling group message')
            await self._handle_message(ctx)

    def _init_aes_key(self):
        """初始化 AES 密钥"""
        config = self.plugin.config
        encoding_aes_key = config.get('encoding_aes_key', '')

        if encoding_aes_key and encoding_aes_key.strip():
            if not HAS_CRYPTO:
                logger.warning(
                    'EncodingAESKey is configured but pycryptodome is not installed. '
                    'Please install it with: pip install pycryptodome'
                )
                return

            try:
                # EncodingAESKey 是 43 字符的 Base64 编码，需要补上 '=' 后解码得到 32 字节的 AES 密钥
                key_str = encoding_aes_key.strip()
                if len(key_str) == 43:
                    key_str += '='
                self._aes_key = base64.b64decode(key_str)
                if len(self._aes_key) != 32:
                    logger.error(f'Invalid EncodingAESKey: decoded length is {len(self._aes_key)}, expected 32')
                    self._aes_key = None
                else:
                    logger.info('AES key initialized successfully for WeCom file decryption')
            except Exception as e:
                logger.error(f'Failed to decode EncodingAESKey: {e}')
                self._aes_key = None
        else:
            logger.info('EncodingAESKey not configured, file decryption disabled')

    def _decrypt_wecom_file(self, encrypted_content: bytes, aes_key_str: str) -> Tuple[Optional[bytes], str]:
        """
        解密企业微信智能机器人加密的文件内容

        企业微信智能机器人使用 AES-256-CBC 加密，与官方SDK中的crypto_utils.py一致：
        - 密钥是Base64编码的（可能缺少padding）
        - IV是AES key的前16字节
        - 使用PKCS#7填充

        Args:
            encrypted_content: 加密的文件内容
            aes_key_str: Base64编码的AES密钥（来自URL的aeskey参数）

        Returns:
            (解密后的内容, 错误信息) - 如果解密成功，错误信息为空字符串
        """
        if not encrypted_content:
            return None, 'encrypted_content is empty'

        if not aes_key_str:
            return None, 'aes_key is empty'

        if not HAS_CRYPTO:
            return None, 'pycryptodome not installed'

        try:
            # Python的base64.b64decode需要正确的padding（长度 % 4 == 0）
            # Node.js的Buffer.from可以容忍缺少'='，所以我们需要手动补齐
            remainder = len(aes_key_str) % 4
            if remainder != 0:
                aes_key_str = aes_key_str + '=' * (4 - remainder)
            key = base64.b64decode(aes_key_str)

            # IV是AES key的前16字节
            iv = key[:16]

            cipher = AES.new(key, AES.MODE_CBC, iv)

            # 确保加密数据对齐到AES块大小（16字节）
            # Node.js的setAutoPadding(false)会静默处理未对齐的数据，
            # 但PyCryptodome会报错
            block_size = 16
            data_remainder = len(encrypted_content) % block_size
            if data_remainder != 0:
                encrypted_content = encrypted_content + b'\x00' * (block_size - data_remainder)

            decrypted = cipher.decrypt(encrypted_content)

            # 去除PKCS#7填充并验证
            if len(decrypted) == 0:
                return None, 'Decrypted data is empty'

            pad_len = decrypted[-1]
            if pad_len < 1 or pad_len > 32 or pad_len > len(decrypted):
                return None, f'Invalid PKCS#7 padding value: {pad_len}'

            # 验证所有填充字节是否一致
            for i in range(len(decrypted) - pad_len, len(decrypted)):
                if decrypted[i] != pad_len:
                    return None, 'Invalid PKCS#7 padding: padding bytes mismatch'

            actual_content = decrypted[: len(decrypted) - pad_len]

            logger.info(f'Successfully decrypted WeCom AI Bot file: {len(actual_content)} bytes')
            return actual_content, ''

        except Exception as e:
            logger.error(f'Failed to decrypt WeCom AI Bot file: {e}')
            return None, str(e)

    def _decrypt_wecom_content(self, encrypted_content: bytes) -> Tuple[Optional[bytes], str]:
        """
        使用全局配置的EncodingAESKey解密企业微信加密的文件内容

        企业微信使用 AES-256-CBC 加密，格式为：
        - 前 16 字节是随机字符串
        - 接下来 4 字节是消息长度（网络字节序）
        - 然后是实际内容
        - 最后是 CorpID（可忽略）

        Args:
            encrypted_content: 加密的文件内容

        Returns:
            (解密后的内容, 错误信息) - 如果解密成功，错误信息为空字符串
        """
        if not self._aes_key:
            return None, 'AES key not initialized'

        if not HAS_CRYPTO:
            return None, 'pycryptodome not installed'

        try:
            # AES-256-CBC 解密，IV 是 AES key 的前 16 字节
            iv = self._aes_key[:16]
            cipher = AES.new(self._aes_key, AES.MODE_CBC, iv)

            # 解密
            decrypted = cipher.decrypt(encrypted_content)

            # 去除 PKCS#7 填充
            pad_len = decrypted[-1]
            if isinstance(pad_len, int):
                # Python 3
                if pad_len < 1 or pad_len > 32:
                    return None, f'Invalid PKCS#7 padding: {pad_len}'
                decrypted = decrypted[:-pad_len]
            else:
                # Python 2 (不太可能，但保险起见)
                pad_len = ord(pad_len)
                if pad_len < 1 or pad_len > 32:
                    return None, f'Invalid PKCS#7 padding: {pad_len}'
                decrypted = decrypted[:-pad_len]

            # 解析格式：16字节随机串 + 4字节长度 + 内容 + CorpID
            if len(decrypted) < 20:
                return None, f'Decrypted content too short: {len(decrypted)} bytes'

            # 跳过 16 字节随机串
            content_with_corpid = decrypted[16:]

            # 读取 4 字节长度（网络字节序，大端）
            content_len = struct.unpack('>I', content_with_corpid[:4])[0]

            # 提取实际内容
            actual_content = content_with_corpid[4 : 4 + content_len]

            logger.info(f'Successfully decrypted WeCom content: {len(actual_content)} bytes')
            return actual_content, ''

        except Exception as e:
            logger.error(f'Failed to decrypt WeCom content: {e}')
            return None, str(e)

    def _try_decrypt_content(self, raw_content: bytes, per_msg_aeskey: str = '') -> bytes:
        """
        尝试解密内容，如果解密失败则返回原始内容

        Args:
            raw_content: 原始文件内容（可能是加密的）
            per_msg_aeskey: 每条消息的AES密钥（来自URL的aeskey参数，用于企业微信智能机器人）

        Returns:
            解密后的内容，或原始内容（如果解密失败）
        """
        # 如果提供了per_msg_aeskey（来自URL参数），优先使用它（企业微信智能机器人的新方式）
        if per_msg_aeskey:
            logger.info(f'Using per-message aeskey for decryption (key length: {len(per_msg_aeskey)})')
            decrypted, error = self._decrypt_wecom_file(raw_content, per_msg_aeskey)
            if decrypted is not None:
                logger.info(
                    f'Decryption with per-message aeskey succeeded: {len(raw_content)} -> {len(decrypted)} bytes'
                )
                return decrypted
            else:
                logger.warning(f'Decryption with per-message aeskey failed ({error}), trying global key')

        # 如果没有per_msg_aeskey或解密失败，尝试使用全局配置的EncodingAESKey
        if not self._aes_key:
            return raw_content

        # 检查内容是否可能是加密的（长度必须是 16 的倍数）
        if len(raw_content) % 16 != 0:
            logger.info('Content length is not a multiple of 16, skipping decryption')
            return raw_content

        # 尝试使用全局配置的EncodingAESKey解密
        decrypted, error = self._decrypt_wecom_content(raw_content)

        if decrypted is not None:
            return decrypted
        else:
            logger.warning(f'Decryption with global key failed ({error}), using original content')
            return raw_content

    async def _handle_message(self, ctx: context.EventContext):
        """处理消息，检测并解析文件"""
        event = ctx.event
        message_chain = event.message_chain

        logger.info(f'Processing message chain with {len(message_chain)} components')

        # 检查消息中是否包含文件
        file_components = []
        image_components = []
        text_content = ''

        for component in message_chain:
            logger.info(f'Component type: {type(component).__name__}')
            if isinstance(component, platform_message.File):
                file_components.append(component)
                logger.info(f'Found file: {component.name}, url: {component.url}, base64: {bool(component.base64)}')
            elif isinstance(component, platform_message.Image):
                image_components.append(component)
                logger.info(f'Found image: {component.url}')
            elif isinstance(component, platform_message.Plain):
                text_content += component.text

        # 如果没有文件（只有图片或文本），直接返回让默认处理
        if not file_components:
            logger.info('No file components found, skipping')
            return

        logger.info(f'Found {len(file_components)} file(s) to process')

        # 获取插件配置
        config = self.plugin.config
        auto_process = config.get('auto_process', True)
        max_content_length = config.get('max_content_length', 50000)
        default_prompt = config.get('default_prompt', '请阅读以下文件内容，并根据用户的要求进行处理：\n\n{content}')
        download_path = config.get('download_path', '')

        # 确定存储路径
        if download_path and download_path.strip():
            storage_path = Path(download_path.strip())
        else:
            storage_path = Path(__file__).parent.parent.parent / 'data' / 'files'
        storage_path.mkdir(parents=True, exist_ok=True)

        # 处理文件
        parsed_contents = []

        for file_comp in file_components:
            try:
                file_name = file_comp.name or f'file_{int(time.time())}'
                raw_content = None
                local_path = None

                # 优先使用 base64 属性（如果有的话）
                if hasattr(file_comp, 'base64') and file_comp.base64:
                    logger.info(f'Using base64 content for file: {file_name}')
                    try:
                        # 处理 data URI 格式
                        base64_data = file_comp.base64
                        if ';base64,' in base64_data:
                            base64_data = base64_data.split(';base64,')[1]
                        raw_content = base64.b64decode(base64_data)

                        # 保存到本地
                        local_path = storage_path / file_name
                        if local_path.exists():
                            name, ext = os.path.splitext(file_name)
                            file_name = f'{name}_{int(time.time())}{ext}'
                            local_path = storage_path / file_name
                        with open(local_path, 'wb') as f:
                            f.write(raw_content)
                        logger.info(f'File saved from base64 to: {local_path}')
                    except Exception as e:
                        logger.error(f'Failed to decode base64: {e}')
                        raw_content = None

                # 如果没有 base64，尝试从 URL 下载
                per_msg_aeskey = ''
                if raw_content is None and file_comp.url:
                    # 打印完整URL用于调试
                    logger.info(f'[DEBUG] Full file URL: {file_comp.url}')
                    logger.info(f'[DEBUG] URL contains aeskey: {"aeskey" in file_comp.url}')
                    logger.info(f'Downloading file: {file_name} from {file_comp.url}')
                    # 下载文件到本地（同时提取URL中的aeskey参数）
                    local_path, per_msg_aeskey = await self._download_file(file_comp.url, file_name, storage_path)
                    logger.info(f'File downloaded to: {local_path}')

                    # 读取下载的文件内容
                    with open(local_path, 'rb') as f:
                        raw_content = f.read()

                if raw_content is None or local_path is None:
                    logger.warning(f'No URL or base64 for file: {file_name}')
                    parsed_contents.append(
                        {
                            'filename': file_name,
                            'type': '文件',
                            'content': '[无法获取文件内容：没有可用的URL或base64数据]',
                        }
                    )
                    continue

                # 尝试解密企业微信加密的文件内容
                # 优先使用URL中的per_msg_aeskey（企业微信智能机器人的新方式）
                original_size = len(raw_content)
                raw_content = self._try_decrypt_content(raw_content, per_msg_aeskey)
                if len(raw_content) != original_size:
                    logger.info(f'Content decrypted: {original_size} -> {len(raw_content)} bytes')
                    # 如果解密成功，重新保存解密后的文件
                    with open(local_path, 'wb') as f:
                        f.write(raw_content)
                    logger.info(f'Decrypted content saved to: {local_path}')

                # 获取MIME类型
                mime_type, _ = mimetypes.guess_type(file_name)
                if not mime_type:
                    mime_type = 'application/octet-stream'
                logger.info(f'File MIME type: {mime_type}')

                # 尝试解码文本内容
                file_text = self._decode_content(raw_content, file_name, mime_type)

                if file_text:
                    parsed_contents.append(
                        {
                            'filename': file_name,
                            'type': SUPPORTED_MIME_TYPES.get(mime_type, '文本文件'),
                            'content': file_text[:max_content_length],
                        }
                    )
                    logger.info(f'Successfully read text file: {file_name}')
                else:
                    # 对于非文本文件，提示用户
                    parsed_contents.append(
                        {
                            'filename': file_name,
                            'type': SUPPORTED_MIME_TYPES.get(mime_type, '文件'),
                            'content': f'[文件已下载到本地: {local_path}，但无法直接读取内容。请安装GeneralParsers插件以支持更多文件格式。]',
                        }
                    )

            except Exception as e:
                logger.error(f'Failed to process file: {e}')
                parsed_contents.append(
                    {
                        'filename': file_comp.name or '未知文件',
                        'type': '文件',
                        'content': f'[下载或处理文件失败: {str(e)}]',
                    }
                )

        # 如果有解析的内容，修改发送给LLM的消息
        if parsed_contents and auto_process:
            # 构建文件内容文本
            content_parts = []
            for item in parsed_contents:
                content_parts.append(f'=== {item["type"]}: {item["filename"]} ===\n{item["content"]}')

            file_content = '\n\n'.join(content_parts)

            # 构建新的消息内容
            if text_content.strip():
                # 用户有额外的文字说明
                new_message = f'{default_prompt.format(content=file_content)}\n\n用户要求: {text_content.strip()}'
            else:
                # 只有文件，使用默认提示
                new_message = default_prompt.format(content=file_content)

            logger.info(f'Setting user_message_alter with {len(new_message)} characters')

            # 修改发送给LLM的消息 - 使用纯文本字符串
            # 这样可以避免模型收到不支持的file_url类型
            event.user_message_alter = new_message

            logger.info('user_message_alter set successfully')

    def _decode_content(self, raw_content: bytes, file_name: str, mime_type: str) -> Optional[str]:
        """尝试将二进制内容解码为文本"""
        # 只对文本类型的文件尝试解码
        if not (mime_type.startswith('text/') or mime_type in ['application/json', 'application/xml']):
            # 对于未知类型，也尝试解码（可能是没有正确识别的文本文件）
            if mime_type == 'application/octet-stream':
                logger.info(f'Unknown MIME type, trying to decode as text: {file_name}')
            else:
                return None

        # 检测编码
        encoding = 'utf-8'
        if HAS_CHARDET:
            try:
                detected = chardet.detect(raw_content)
                encoding = detected.get('encoding', 'utf-8') or 'utf-8'
                confidence = detected.get('confidence', 0)
                logger.info(f'Detected encoding: {encoding} (confidence: {confidence})')
            except Exception as e:
                logger.warning(f'chardet detection failed: {e}')

        # 尝试使用检测到的编码解码
        file_text = None
        try:
            file_text = raw_content.decode(encoding)
            logger.info(f'Successfully decoded with encoding: {encoding}')
            return file_text
        except (UnicodeDecodeError, LookupError) as e:
            logger.warning(f'Failed to decode with {encoding}: {e}')

        # 如果检测到的编码失败，尝试常见的编码
        for fallback_encoding in [
            'utf-8',
            'gbk',
            'gb2312',
            'gb18030',
            'big5',
            'utf-16',
            'utf-16-le',
            'utf-16-be',
            'latin-1',
        ]:
            if fallback_encoding == encoding:
                continue
            try:
                file_text = raw_content.decode(fallback_encoding)
                logger.info(f'Successfully decoded with fallback encoding: {fallback_encoding}')
                return file_text
            except (UnicodeDecodeError, LookupError):
                continue

        # 如果所有编码都失败，使用 errors='replace'
        logger.warning(f"All encodings failed, using errors='replace'")
        return raw_content.decode('utf-8', errors='replace')

    def _normalize_cos_url(self, url: str) -> str:
        """
        规范化COS下载URL

        处理企业微信返回的特殊URL格式，例如：
        原始: ...?sign=q-sign-algorithm%3Dsha1%26q-ak%3Dxxx...?aeskey=yyy
        规范化后: ...?q-sign-algorithm=sha1&q-ak=xxx...&aeskey=yyy

        Args:
            url: 原始URL

        Returns:
            规范化后的URL
        """
        # 处理URL中存在多个?的情况（第二个?应该是&）
        # 例如: ...?sign=xxx?aeskey=yyy -> 先分割处理
        if url.count('?') > 1:
            # 找到第一个?的位置
            first_q = url.index('?')
            # 把后续的?替换为&
            url = url[:first_q + 1] + url[first_q + 1:].replace('?', '&')
            logger.debug(f'Fixed multiple ? in URL')

        # 解析URL
        parsed = urlparse(url)
        query_params = parse_qs(parsed.query, keep_blank_values=True)

        # 检查是否有sign参数，其值包含编码后的COS签名参数
        if 'sign' in query_params:
            sign_value = query_params['sign'][0]
            # 解码sign参数的值
            decoded_sign = unquote(sign_value)

            # 检查是否是COS签名格式 (包含q-sign-algorithm等)
            if 'q-sign-algorithm' in decoded_sign:
                logger.info('Detected encoded COS signature in sign parameter, normalizing URL')

                # 构建新的查询字符串
                # 从decoded_sign中提取参数，加上其他参数（如aeskey）
                new_query_parts = [decoded_sign]

                # 添加其他参数（除了sign）
                for key, values in query_params.items():
                    if key != 'sign':
                        for value in values:
                            new_query_parts.append(f'{key}={value}')

                new_query = '&'.join(new_query_parts)

                # 重建URL
                normalized_url = f'{parsed.scheme}://{parsed.netloc}{parsed.path}?{new_query}'
                logger.debug(f'Normalized URL: {normalized_url[:100]}...')
                return normalized_url

        return url

    async def _download_file(self, url: str, filename: str, storage_path: Path) -> Tuple[Path, str]:
        """
        下载文件到本地

        Args:
            url: 文件下载URL（可能包含?aeskey=xxx参数）
            filename: 文件名
            storage_path: 存储路径

        Returns:
            (本地文件路径, aeskey参数) - aeskey用于解密企业微信智能机器人的文件
        """
        # 规范化URL（处理企业微信的特殊签名格式）
        normalized_url = self._normalize_cos_url(url)
        if normalized_url != url:
            logger.info(f'URL normalized for COS signature compatibility')

        # 解析URL，提取aeskey参数
        parsed_url = urlparse(normalized_url)
        query_params = parse_qs(parsed_url.query)
        aeskey = query_params.get('aeskey', [''])[0]

        if aeskey:
            logger.info(f'Found aeskey in URL (length: {len(aeskey)}), will use for decryption')

        # 确保文件名唯一
        file_path = storage_path / filename
        if file_path.exists():
            name, ext = os.path.splitext(filename)
            filename = f'{name}_{int(time.time())}{ext}'
            file_path = storage_path / filename

        # 下载文件
        async with aiohttp.ClientSession() as session:
            async with session.get(normalized_url) as response:
                if response.status == 200:
                    content = await response.read()
                    with open(file_path, 'wb') as f:
                        f.write(content)
                    return file_path, aeskey
                else:
                    # 获取更多错误信息
                    error_body = await response.text()
                    logger.error(f'Download failed with status {response.status}: {error_body[:500]}')
                    raise Exception(f'下载文件失败，HTTP状态码: {response.status}')
